/**
 * Calcio: en mg
 * Fósforo: en mg
 * Oxalatos: en mg
 * HdC, proteinas y grasas: g por cada 100g
 */
food = [
	//oxalatos bajos
	{
		"name" : "Naranja",
		"description" : "Naranja pelada.",
		"icono" : "naranja",
		"color" : "#000000",
		"calcium" : 40,
		"phosphor" : 14,
		"oxalates" : 10,
		"cal" : 13,
		"carbohydrates" : 11.8,
		"fats" : 0.1,
		"proteins" : 0.9
	},
	{
		"name" : "Col china",
		"description" : "Bok Choy, cruda.",
		"icono" : "colchina",
		"color" : "#000000",
		"calcium" : 105,
		"phosphor" : 37,
		"oxalates" : 1,
		"cal" : 13,
		"carbohydrates" : 2.2,
		"fats" : 0.2,
		"proteins" : 1.5
	},
	{
		"name" : "Hibiscos",
		"description" : "Flor hibiscus.",
		"icono" : "hibiscus",
		"color" : "#000000",
		"calcium" : 27,
		"phosphor" : 10,
		"oxalates" : 1,
		"cal" : 37,
		"carbohydrates" : 7.4,
		"fats" : 0.7,
		"proteins" : 0.4
	},
	{
		"name" : "Higo",
		"description" : "Higo crudo pelado.",
		"icono" : "higo",
		"color" : "#000000",
		"calcium" : 35,
		"phosphor" : 14,
		"oxalates" : 23,
		"cal" : 74,
		"carbohydrates" : 19.2,
		"fats" : 0.3,
		"proteins" : 0.8
	},
	{
		"name" : "Papaya",
		"description" : "",
		"icono" : "papaya",
		"color" : "#000000",
		"calcium" : 20,
		"phosphor" : 10,
		"oxalates" : 1,
		"cal" : 43,
		"carbohydrates" : 10.8,
		"fats" : 0.3,
		"proteins" : 0.5
	},
	{
		"name" : "Kale",
		"description" : "",
		"icono" : "kale",
		"color" : "#000000",
		"calcium" : 150,
		"phosphor" : 92,
		"oxalates" : 3,
		"cal" : 49,
		"carbohydrates" : 8.8,
		"fats" : 0.9,
		"proteins" : 4.3
	},
	{
		"name" : "Col",
		"description" : "Col cruda.",
		"icono" : "col",
		"color" : "#000000",
		"calcium" : 40,
		"phosphor" : 26,
		"oxalates" : 1,
		"cal" : 25,
		"carbohydrates" : 5.8,
		"fats" : 0.1,
		"proteins" : 1.3
	},
	{
		"name" : "Pomelo",
		"description" : "",
		"icono" : "pomelo",
		"color" : "#000000",
		"calcium" : 12,
		"phosphor" : 8,
		"oxalates" : 8,
		"cal" : 33,
		"carbohydrates" : 8.4,
		"fats" : 0.1,
		"proteins" : 0.7
	},
	{
		"name" : "Zanahoria",
		"description" : "Zanahoria cruda.",
		"icono" : "zanahoria",
		"color" : "#000000",
		"calcium" : 33,
		"phosphor" : 35,
		"oxalates" : 30,
		"cal" : 41,
		"carbohydrates" : 9.6,
		"fats" : 0.2,
		"proteins" : 0.9
	},
	{
		"name" : "Calabacín",
		"description" : "Calabacín crudo.",
		"icono" : "calabacin",
		"color" : "#000000",
		"calcium" : 33,
		"phosphor" : 36,
		"oxalates" : 2,
		"cal" : 40,
		"carbohydrates" : 10.4,
		"fats" : 0.1,
		"proteins" : 0.8
	},
	{
		"name" : "Mango",
		"description" : "",
		"icono" : "mango",
		"color" : "#000000",
		"calcium" : 11,
		"phosphor" : 14,
		"oxalates" : 3,
		"cal" : 60,
		"carbohydrates" : 15,
		"fats" : 0.4,
		"proteins" : 0.8
	},
	{
		"name" : "Brócoli",
		"description" : "Brócoli crudo.",
		"icono" : "brocoli",
		"color" : "#000000",
		"calcium" : 47,
		"phosphor" : 66,
		"oxalates" : 190,
		"cal" : 34,
		"carbohydrates" : 6.6,
		"fats" : 0.4,
		"proteins" : 2.8
	},
	{
		"name" : "Fresa",
		"description" : "",
		"icono" : "strawberry",
		"color" : "#ff0000",
		"calcium" : 16,
		"phosphor" : 24,
		"oxalates" : 1.9,
		"cal" : 32,
		"carbohydrates" : 7.7,
		"fats" : 0.3,
		"proteins" : 0.7
	},
	{
		"name" : "Pepino",
		"description" : "",
		"icono" : "pepino",
		"color" : "#000000",
		"calcium" : 16,
		"phosphor" : 24,
		"oxalates" : 1,
		"cal" : 15,
		"carbohydrates" : 3.6,
		"fats" : 0.1,
		"proteins" : 0.7
	},
	{
		"name" : "Calabaza",
		"description" : "Calabaza cruda sin piel.",
		"icono" : "calabaza",
		"color" : "#000000",
		"calcium" : 20,
		"phosphor" : 32,
		"oxalates" : 40,
		"cal" : 20,
		"carbohydrates" : 4.3,
		"fats" : 0.2,
		"proteins" : 1.2
	},
	{
		"name" : "Manzana",
		"description" : "Manzana sin piel.",
		"icono" : "apple",
		"color" : "#ff0000",
		"calcium" : 6,
		"phosphor" : 11,
		"oxalates" : 10,
		"cal" : 52,
		"carbohydrates" : 13.8,
		"fats" : 0.2,
		"proteins" : 0.3
	},
	{
		"name" : "Melón",
		"description" : "Melón pelado.",
		"icono" : "melon",
		"color" : "#000000",
		"calcium" : 6,
		"phosphor" : 11,
		"oxalates" : 2,
		"cal" : 36,
		"carbohydrates" : 9.1,
		"fats" : 0.1,
		"proteins" : 0.5
	},
	{
		"name" : "Tomate",
		"description" : "Tomate rojo crudo.",
		"icono" : "tomate",
		"color" : "#000000",
		"calcium" : 13,
		"phosphor" : 28,
		"oxalates" : 4,
		"cal" : 23,
		"carbohydrates" : 5.1,
		"fats" : 0.2,
		"proteins" : 1.2
	},
	{
		"name" : "Melocotón",
		"description" : "",
		"icono" : "melocoton",
		"color" : "#000000",
		"calcium" : 6,
		"phosphor" : 20,
		"oxalates" : 1,
		"cal" : 39,
		"carbohydrates" : 9.5,
		"fats" : 0.3,
		"proteins" : 0.9
	},
	{
		"name" : "Granada",
		"description" : "Granada pelada.",
		"icono" : "granada",
		"color" : "#000000",
		"calcium" : 10,
		"phosphor" : 36,
		"oxalates" : 14,
		"cal" : 83,
		"carbohydrates" : 18.7,
		"fats" : 1.2,
		"proteins" : 1.7
	},
	{
		"name" : "Pimiento rojo",
		"description" : "Pipiento rojo crudo.",
		"icono" : "pimienta",
		"color" : "#000000",
		"calcium" : 7,
		"phosphor" : 26,
		"oxalates" : 117,
		"cal" : 31,
		"carbohydrates" : 6,
		"fats" : 0.3,
		"proteins" : 1
	},
	{
		"name" : "Guisantes",
		"description" : "Guisantes crudos.",
		"icono" : "guisante",
		"color" : "#000000",
		"calcium" : 25,
		"phosphor" : 108,
		"oxalates" : 1,
		"cal" : 81,
		"carbohydrates" : 14.4,
		"fats" : 0.4,
		"proteins" : 5.4
	},
	{
		"name" : "Banana",
		"description" : "",
		"icono" : "banana",
		"color" : "#000000",
		"calcium" : 5,
		"phosphor" : 22,
		"oxalates" : 3,
		"cal" : 89,
		"carbohydrates" : 22.8,
		"fats" : 0.3,
		"proteins" : 1.1
	},
	{
		"name" : "Sandía",
		"description" : "Sandía pelada.",
		"icono" : "sandia",
		"color" : "#000000",
		"calcium" : 7,
		"phosphor" : 112,
		"oxalates" : 1,
		"cal" : 30,
		"carbohydrates" : 7.5,
		"fats" : 0.1,
		"proteins" : 0.6
	},
];